#ifndef Menu_H
#define Menu_H

#define courseDataFile "course_data.txt"
#define scheduleDataFile "schedule_preferences.txt"

#include <vector>
#include <string>
#include <fstream>
#include "CourseModule.h"
#include "CourseGraph.h"
#include "Scheduler.h"

/**
 * @brief Temporary class to drive the program giving the option to add, remove, and edit courses in a list
 * @details Meant to be replaced in the future with an actual object oriented design and GUI
 * @details I started this project when I didn't know much, that's why it's like this
*/
class Menu {
private:

	/**
	 * @brief Container holding all the user's courses that have been added.
	*/
	CourseGraph Courses;

	/**
	 * @brief Handles generating schedules
	*/
	Scheduler CourseScheduler;
	
	/**
	 * @brief Asks to input a course then retries if the course entered is invalid
	 * @return Pointer to the course entered. Returns nullptr if course entered does not exist in the list of courses
	*/
	CourseModule *inputValidCourse();

	/**
	 * @brief Reads a line of courses from user input and repeats when input is invalid
	 * @details If any of the courses entered do not exist in the list of courses, the course is added to the list of courses
	 * @return Vector containing all the courses entered
	*/
	std::vector<CourseModule*> inputValidCourses();

	/**
	 * @brief Asks to input a new course then retries if the course entered is invalid
	 * @details If the course entered does not exist, we create it
	 * @return Pointer to a course entered by the user (new or existing)
	*/
	CourseModule *inputNewValidCourse();

	/**
	 * @brief Asks to input a season and a year (Ex: Spring 2020) and retries if input is invalid
	 * @param message The message you want to display asking for input
	 * @return Empty semester entered by the user containing only the season and the year
	*/
	Semester enterSemester(std::string message = "Enter a semester (Ex: Spring 2020): ") const;

	/**
	 * @brief Whenever we update the course graph, we should update the scheduler because the scheduler would have an old data set to work with
	*/
	void updateScheduler();

public:
	/**
	 * @brief Constructor to read data from a file to populate the list of courses
	*/
	Menu ();

	/**
	 * @brief Prints a welcome message then runs the main menu
	*/
	void runMenu();
	
	/**
	 * @brief Gives a list of options and asks for user to select one then performs that action when entered
	*/
	void mainMenu();
	
	/**
	 * @brief Allows user to add a course by entering the course subject and number
	 * @details Allows user to also enter information for the course before finishing
	*/
	void subMenuCourseAdd();

	/**
	 * @brief Asks user which course to remove then removes the course specified
	*/
	void subMenuCourseRemove();

	/**
	 * @brief Allows the user to edit a course's information (not including course subject and number)
	*/
	void subMenuCourseEdit();

	/**
	 * @brief Searches the list of courses for 
	*/
	void subMenuCourseSearch();

	/**
	 * @brief Allows user to generate a schedule based on the courses entered
	 * @details Use can disallow semesters, 
	*/
	void subMenuCourseScheduler();

	/**
	 * @brief Allows user to add a restriction to the course scheduler
	 * @details User can restrict semesters, individual semesters, or courses for an individual semester
	*/
	void addRestriction();

	/**
	 * @brief Allows user to remove a restriction from the course scheduler
	*/
	void removeRestriction();

	/**
	 * @brief Prints all restrictions on the schedule generator
	*/
	void printScheduleRestrictions() const;

	/**
	 * @brief Prints the schedule generated by the course scheduler 
	*/
	void printSchedule(Semester s) const;

	/**
	 * @brief Gives user a menu to edit a course allowing them to change different attributes
	 * @param c Course being edited
	*/
	void editCourse(CourseModule &c);
	
	/**
	 * @brief Enters all courses (format ex: CECS 100) from a string into a course's prerequisites. Does not check validity
	 * @param course Course we're adding prerequisites to
	 * @param str String we're reading courses from
	*/
	void readPrerequisites(CourseModule &course, std::string str);

	/**
	 * @brief Adds multiple courses to the list of prerequisites of a course
	 * @param course The course receiving the list of prerequisites
	 * @param prereqs Vector containing courses that are prerequisites for course
	*/
	void addMultiplePrereqs(CourseModule *course, const std::vector<CourseModule *> &prereqs);

	/**
	 * @brief Prints all courses' subjects and numbers in the list of courses
	*/
	void printAllCourses();

	/**
	 * @brief Prints all the courses' subjects and numbers that have incomplete data
	*/
	void printAllIncompleteDataCourses();

	/**
	 * @brief Prints all data for each course in the list of courses
	*/
	void printAllCourseData();

	/**
	 * @brief Gets all course data as a string
	 * @param course Course we're getting data from
	 * @return String containing all data for the specified course
	*/
	std::string fullCourseInfo(const CourseModule &course);

};

#endif